name: flutter_debug_tools
description: A set of tools to help find and debug UI or performance issues from the Flutter app itself.
version: 0.0.5+6
repository: https://github.com/LiquidatorCoder/flutter_debug_tools
topics: [debug, color-picker, performance, ui, size]

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^11.1.1
  flutter:
    sdk: flutter
  loggy: ^2.0.3
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: Menu of flutter debug tools.
    path: screenshots/image.png

flutter:
