import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter_debug_tools/src/debug_log_store.dart';

/// DebugLogsViewer is a widget that displays a list of logs.
/// Allows for the inspection of log messages generated by the application.
class DebugLogsViewer extends StatelessWidget {
  const DebugLogsViewer({
    super.key,
    required this.onTap,
  });
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: GestureDetector(
          onTap: onTap,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Row(
                children: [
                  const Padding(
                    padding: EdgeInsets.symmetric(horizontal: 16.0),
                    child: Text(
                      'Debug Logs',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Colors.black,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  const Spacer(),
                  Transform.rotate(
                    angle: pi / 4,
                    child: IconButton(
                      onPressed: onTap,
                      icon: const Text(
                        "+",
                        style: TextStyle(fontSize: 24),
                      ),
                    ),
                  ),
                  IconButton(
                    onPressed: DebugLogStore.instance.clear,
                    icon: const Icon(Icons.delete_outline),
                  ),
                ],
              ),
              Expanded(
                child: ValueListenableBuilder<List<DebugLogEntry>>(
                  valueListenable: DebugLogStore.instance.logs,
                  builder: (context, logs, _) {
                    if (logs.isEmpty) {
                      return const Center(
                        child: Text(
                          'No logs captured yet',
                          style: TextStyle(fontSize: 12, color: Colors.black54),
                        ),
                      );
                    }

                    return ListView.builder(
                      itemCount: logs.length,
                      itemBuilder: (context, index) {
                        final entry = logs[logs.length - 1 - index];

                        return ListTile(
                          visualDensity: VisualDensity.compact,
                          leading: Container(
                            width: 16,
                            height: 16,
                            decoration: BoxDecoration(
                              color: _getLogColor(entry.level),
                              shape: BoxShape.circle,
                            ),
                            child: Center(
                              child: Text(
                                _getLevelTitle(entry.level).substring(0, 1),
                                style: const TextStyle(
                                  fontSize: 6,
                                  color: Colors.white,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            ),
                          ),
                          title: Text(
                            entry.message,
                            maxLines: 8,
                            overflow: TextOverflow.ellipsis,
                            softWrap: true,
                            style: const TextStyle(
                              fontSize: 12,
                              color: Colors.black,
                            ),
                          ),
                          subtitle: Text(
                            _getLevelTitle(entry.level),
                            style: TextStyle(
                              fontSize: 10,
                              color: _getLogColor(entry.level),
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        );
                      },
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Color _getLogColor(DebugLogLevel level) {
    switch (level) {
      case DebugLogLevel.error:
        return Colors.red;
      case DebugLogLevel.warning:
        return Colors.orange.withValues(alpha: 0.8);
      case DebugLogLevel.debug:
        return Colors.blue.withValues(alpha: 0.8);
      case DebugLogLevel.verbose:
        return Colors.purple.withValues(alpha: 0.8);
      case DebugLogLevel.info:
        return Colors.green.withValues(alpha: 0.8);
    }
  }

  String _getLevelTitle(DebugLogLevel level) {
    switch (level) {
      case DebugLogLevel.error:
        return 'ERROR';
      case DebugLogLevel.warning:
        return 'WARNING';
      case DebugLogLevel.debug:
        return 'DEBUG';
      case DebugLogLevel.verbose:
        return 'VERBOSE';
      case DebugLogLevel.info:
        return 'INFO';
    }
  }
}
